/**
 * Registers the service worker for PWA offline functionality
 *
 * This utility should be called once at the application entry point.
 * The service worker is automatically generated by vite-plugin-pwa during build.
 */
export function registerServiceWorker(): void {
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      navigator.serviceWorker
        .register('/sw.js')
        .then((registration) => {
          console.log('Service Worker registered successfully:', registration.scope);
        })
        .catch((error) => {
          console.error('Service Worker registration failed:', error);
        });
    });
  }
}
